title: <p align="center"> Amit Kumar Chaudhary </p>
logo: /assets/img/profile photo.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/thenameisamitchaudhary/">LinkedIn</a> |
  <a href="https://github.com/amit-kumar-chaudhary">GitHub</a> |
  <a href="mailto:amitchaudhary1905@gmail.com">E-Mail</a> |
  <a href="https://wa.me/+917054736232">WhatsApp</a>
 
  <br>  
  An ambitious and motivated individual with a profound interest in Data Science and a specialization in Deep Learning.
  I am currently pursuing my studies in Deep Learning, where I have acquired a strong foundation in machine learning 
  algorithms, neural networks, and advanced data analysis techniques.
  I am eager to contribute my knowledge, passion, and dedication to a dynamic organization where I can collaborate 
  with like-minded professionals, engage in cutting-edge projects, and continue learning and growing as a Data Scientist.
  <br>
  </p>



theme: jekyll-theme-minimal
